name = "MiniZinc"
uuid = "a7f392d2-6c35-496e-b8cc-0974fbfcbf91"
authors = ["odow <o.dowson@gmail.com>"]
version = "0.3.5"

[deps]
Chuffed_jll = "77125aae-c893-5498-99e3-e30470bfa328"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MiniZinc_jll = "3677d96b-3d39-5184-a844-8e8b2839af35"

[compat]
Chuffed_jll = "=0.10.4"
MathOptInterface = "1.21"
MiniZinc_jll = "=2.7.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
